spring.application.name=hello


#나의 커스텀 설정들을 이 안에 정의 할 수 있음!!!
# property=value (띄어쓰기 조심)

my.custom.msg=Hello, Boot!
my-custom-number=42


# 뷰 리졸버 접두사/접미사 세팅
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp